name: Deploy Documentation to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "site/**"

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  pages: write
  contents: read
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: site

jobs:
  deploy:
    name: "Build & Publish Documentation to GitHub Pages"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "site/package-lock.json"

      - name: "Install Dependencies"
        run: npm ci

      - name: "Build Documentation"
        run: npm run docs:build

      - name: "Setup Pages"
        uses: actions/configure-pages@v4

      - name: "Upload Build Artifact"
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./site/docs/dist"

      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4
